### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by szpak** [MShekow/renovate-pr-visualization#3]
It would be good to support also GitLab as a Git repository.

**Comment by MShekow** [comment]
Agreed. I have my hands full these days with other projects, but I'm planning to add GitLab support in January. Unless you or someone else wants to contribute it.

**Comment by szpak** [comment]
I took a look at the code and GitHub part seems to be highly coupled with the rest. Probably bigger some refactoring with extracting the Git-provider related code is needed. It's your code, you know it very well and in my option you are the best person to do it properly.

Impatiently waiting for January :)

**Comment by MShekow** [comment]
Jup, the coupling is making it more difficult to extend the code. I'm indeed planning to add an abstraction layer.

**Comment by MShekow** [comment]
By the way, in case you have some free time and interest, you could research which SDK calls (using [this Gitlab SDK](https://python-gitlab.readthedocs.io)) are equivalent to the [githubkit](https://github.com/yanyongyu/githubkit) SDK calls I'm making in the code. That would take a lot of work off my plate.

**Comment by HonkingGoose** [comment]
Looks like you switched from `githubkit` to `PyGitHub` recently:

- 567ca1689c9522430d10bd4d5552cdafa0533fc4

So is this still relevant?

> By the way, in case you have some free time and interest, you could research which SDK calls (using [this Gitlab SDK](https://python-gitlab.readthedocs.io)) are equivalent to the [githubkit](https://github.com/yanyongyu/githubkit) SDK calls I'm making in the code. That would take a lot of work off my plate.

**Comment by MShekow** [comment]
Yes, still relevant. The wording is now:

in case you have some free time and interest, you could research which SDK calls (using [this Gitlab SDK](https://python-gitlab.readthedocs.io/)) are equivalent to the [PyGithub](https://pygithub.readthedocs.io) SDK calls I'm making in the code. That would take a lot of work off my plate.
