### ISSUE TITLE
[GitLab] Closed Renovete PRs are not detected

### ISSUE THREAD

**Issue by szpak** [MShekow/renovate-pr-visualization#9]
I gave the new GitLab backend a try and it detected the PRs/MRs nicely, however, I observe a problem with closed MRs. They seem to be not covered:

![image](https://github.com/MShekow/renovate-pr-visualization/assets/148013/6c99be66-3d3a-4877-9485-c68e164c3546)

(looking in a MR history for that project, I see a few merged Renovate MRs).

It might be a problem with my setup, but @robrobert99 does it show the closed MRs in your case?

GitLab self hosted: 17.0.2.

Btw, I even added `get_all=True` (#8) to getting the commit list, but it didn't help.

**Comment by szpak** [comment]
Btw, what's interesting, in "Table of all dependencies", I see the dependencies with "close type" merge or closed.

But in the "Renovate PR details" table on the dashboard page the closed/merged MRs/dependencies are not shown (only currently open).

**Comment by robrobert99** [comment]
Do you mean the close duration? In my setup it shows the closed MRs.

**Comment by szpak** [comment]
On my graph (see above), the open dependencies are in the increasing trend only (although, some of them have been closed). I chose 1 week interval and 60 weeks history. Do you have any idea why it behaves that way? Could possible changes in GitLab 17 API be a problem?

**Comment by szpak** [comment]
@MShekow What do you propose to do to diagnose that? Can any extra logging be enabled?

**Comment by MShekow** [comment]
> @MShekow What do you propose to do to diagnose that? Can any extra logging be enabled?

If you think the database table content of the dependencies looks correct, the problem is most likely with the SQL query that generates the data for the graph. You can edit it directly in Metabase. Alternatively, the `README.md` has an expandable block ("Example for SQL query") which also shows the query, so you can also execute it on PostgreSQL directly.

**Comment by szpak** [comment]
Strange, today I see "something" in the "close duration" widget and also on the main dashboard. Maybe there was something to be processed in the background (?). Closing for now.
